# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: knife-chop 0.0.9 ruby lib

Gem::Specification.new do |s|
  s.name = "knife-chop"
  s.version = "0.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christo De Lange"]
  s.date = "2013-10-30"
  s.description = "Knife plugin to assist with the upload and sync of Chef server assets like roles, environments and cookbooks allowing for multiple parts to be uploaded at once to multiple environments. Resources can be matched with regular expressions."
  s.email = "opscode@dldinternet.com"
  s.executables = ["chop"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/chop",
    "knife-chop.gemspec",
    "lib/chef/knife/chop/chef_data_bag_item.rb",
    "lib/chef/knife/chop/chef_environment.rb",
    "lib/chef/knife/chop/chef_knife.rb",
    "lib/chef/knife/chop/chef_part.rb",
    "lib/chef/knife/chop/chef_role.rb",
    "lib/chef/knife/chop/cookbook_upload.rb",
    "lib/chef/knife/chop/data_bag_from_file.rb",
    "lib/chef/knife/chop/environment_from_file.rb",
    "lib/chef/knife/chop/errors.rb",
    "lib/chef/knife/chop/logging.rb",
    "lib/chef/knife/chop/role_from_file.rb",
    "lib/chef/knife/chop/translate.rb",
    "lib/chef/knife/chop/translate/eden.rb",
    "lib/chef/knife/chop/translate/rbeautify.rb",
    "lib/chef/knife/chop/ui.rb",
    "lib/chef/knife/chop_base.rb",
    "lib/chef/knife/chop_translate.rb",
    "lib/chef/knife/chop_upload.rb",
    "lib/eden/CHANGELOG",
    "lib/eden/LICENSE",
    "lib/eden/README.md",
    "lib/eden/Rakefile",
    "lib/eden/bin/eden",
    "lib/eden/lib/eden.rb",
    "lib/eden/lib/eden/defaults.rb",
    "lib/eden/lib/eden/formatter.rb",
    "lib/eden/lib/eden/formatters/block_formatter.rb",
    "lib/eden/lib/eden/formatters/indenter.rb",
    "lib/eden/lib/eden/formatters/white_space_cleaner.rb",
    "lib/eden/lib/eden/line.rb",
    "lib/eden/lib/eden/parser.rb",
    "lib/eden/lib/eden/source.rb",
    "lib/eden/lib/eden/source_file.rb",
    "lib/eden/lib/eden/token.rb",
    "lib/eden/lib/eden/tokenizer.rb",
    "lib/eden/lib/eden/tokenizers/basic_tokenizer.rb",
    "lib/eden/lib/eden/tokenizers/delimited_literal_tokenizer.rb",
    "lib/eden/lib/eden/tokenizers/number_tokenizer.rb",
    "lib/eden/lib/eden/tokenizers/operator_tokenizer.rb",
    "lib/eden/lib/eden/tokenizers/regex_tokenizer.rb",
    "lib/eden/lib/eden/tokenizers/string_tokenizer.rb",
    "lib/eden/test/array_literal_tokenization_test.rb",
    "lib/eden/test/basic_tokenization_test.rb",
    "lib/eden/test/block_formatter_test.rb",
    "lib/eden/test/class_var_token_test.rb",
    "lib/eden/test/identifier_token_test.rb",
    "lib/eden/test/indenter_test.rb",
    "lib/eden/test/instance_var_token_test.rb",
    "lib/eden/test/number_tokenization_test.rb",
    "lib/eden/test/operator_tokenization_test.rb",
    "lib/eden/test/regex_tokenization_test.rb",
    "lib/eden/test/single_character_tokenization_test.rb",
    "lib/eden/test/string_tokenization_test.rb",
    "lib/eden/test/symbol_tokenization_test.rb",
    "lib/eden/test/test_helper.rb",
    "lib/eden/test/white_space_cleaner_test.rb",
    "lib/eden/test/whitespace_token_test.rb",
    "lib/knife-chop.rb",
    "lib/knife-chop/version.rb",
    "lib/knife-chop_version.rb",
    "lib/ruby-beautify/Gemfile",
    "lib/ruby-beautify/LICENSE",
    "lib/ruby-beautify/README.md",
    "lib/ruby-beautify/RELEASE.md",
    "lib/ruby-beautify/Rakefile",
    "lib/ruby-beautify/bin/rbeautify",
    "lib/ruby-beautify/lib/beautifier.rb",
    "lib/ruby-beautify/lib/ruby-beautify.rb",
    "lib/ruby-beautify/lib/ruby-beautify/block_end.rb",
    "lib/ruby-beautify/lib/ruby-beautify/block_matcher.rb",
    "lib/ruby-beautify/lib/ruby-beautify/block_start.rb",
    "lib/ruby-beautify/lib/ruby-beautify/config/ruby.rb",
    "lib/ruby-beautify/lib/ruby-beautify/language.rb",
    "lib/ruby-beautify/lib/ruby-beautify/line.rb",
    "lib/ruby-beautify/lib/ruby-beautify/version.rb",
    "lib/ruby-beautify/ruby-beautify.gemspec",
    "lib/ruby-beautify/spec/fixtures/ruby.yml",
    "lib/ruby-beautify/spec/rbeautify/block_matcher_spec.rb",
    "lib/ruby-beautify/spec/rbeautify/block_start_spec.rb",
    "lib/ruby-beautify/spec/rbeautify/config/ruby_spec.rb",
    "lib/ruby-beautify/spec/rbeautify/line_spec.rb",
    "lib/ruby-beautify/spec/rbeautify_spec.rb",
    "lib/ruby-beautify/spec/spec_helper.rb",
    "spec/knife-chop_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/dldinternet/knife-chop"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.5"
  s.summary = "Knife plugin to ease the upload and sync of Chef server assets"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<knife-chop>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14"])
      s.add_development_dependency(%q<rake>, ["~> 10.1"])
      s.add_development_dependency(%q<sdoc>, ["~> 0.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.8"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.14"])
      s.add_dependency(%q<rake>, ["~> 10.1"])
      s.add_dependency(%q<sdoc>, ["~> 0.3"])
      s.add_dependency(%q<jeweler>, [">= 1.8.8"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.14"])
    s.add_dependency(%q<rake>, ["~> 10.1"])
    s.add_dependency(%q<sdoc>, ["~> 0.3"])
    s.add_dependency(%q<jeweler>, [">= 1.8.8"])
  end
end

